#!/bin/sh

clock=$(date '+%I')

case "$clock" in
"00") icon=" " ;; # nf-weather-time-12
"01") icon=" " ;; # nf-weather-time-1
"02") icon=" " ;; # nf-weather-time-2
"03") icon=" " ;; # nf-weather-time-3
"04") icon=" " ;; # nf-weather-time-4
"05") icon=" " ;; # nf-weather-time-5
"06") icon=" " ;; # nf-weather-time-6
"07") icon=" " ;; # nf-weather-time-7
"08") icon=" " ;; # nf-weather-time-8
"09") icon=" " ;; # nf-weather-time-9
"10") icon=" " ;; # nf-weather-time-10
"11") icon=" " ;; # nf-weather-time-11
"12") icon=" " ;; # nf-weather-time-12 (loop back to 12)
esac

case $BLOCK_BUTTON in
1) notify-send "This Month" "$(cal | sed "s/\<$(date +'%e')\>/<b><span color='red'>&<\/span><\/b>/")" && notify-send "Appointments" "$(calcurse -d3)" ;;
2) setsid -f "$TERMINAL" -e calcurse ;;
3) notify-send " Time/date module" "\- Left click to show upcoming appointments for the next three days via \`calcurse -d3\` and show the month via \`cal\`
- Middle click opens calcurse if installed" ;;
6) "$TERMINAL" -e "$EDITOR" "$0" ;;
esac

date "+%Y %b %d (%a) $icon%I:%M%p"
